name: shorten_url

services:
  postgres:
    container_name: shorten_url
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - data:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 5050:8080

volumes:
  data: {}
