//go:build ignore

package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
)

type packageData struct {
	Package string
	Path    string
	Structs []structData
}

type structData struct {
	Type    string
	Entries []templateEntry
}

type templateEntry struct {
	Name      string
	TypeValue string
}

const templateStr = `
// Code generated by go generate; DO NOT EDIT.

package {{.Package}}

{{- range .Structs}}
func (t *{{.Type}}) Reset() {
	if t == nil {
		return
	}

	{{range .Entries}}
	{{- if eq .TypeValue "int" "int8" "int16" "int32" "int64" "uint" "uint8" "uint16" "uint32" "uint64"}}
	t.{{.Name}} = 0
	{{- else if eq .TypeValue "string"}}
	t.{{.Name}} = ""
	{{- else if eq .TypeValue "bool"}}
	t.{{.Name}} = false
	{{- else if eq .TypeValue "map"}}
	t.{{.Name}} = nil
	{{- else if eq .TypeValue "slice"}}
	t.{{.Name}} = t.{{.Name}}[:0]
	{{- else if eq .TypeValue "pointer"}}
	t.{{.Name}} = nil
	{{- else if eq .TypeValue "unknown"}}
	// Сложный тип t.{{.Name}}
	{{- end}}
	{{- end}}
}
{{end}}
`

func main() {
	flag.Parse()

	fmt.Println(flag.Args())
	cfg := &packages.Config{
		Mode:  packages.NeedName | packages.NeedFiles | packages.NeedSyntax,
		Tests: false,
	}

	pkgs, err := packages.Load(cfg, "github.com/Albert-Ti/go-musthave-shortener-tpl/...")
	if err != nil {
		panic(err)
	}

	// ключ — уникальный путь пакета, значение — накопленные данные
	packagesMap := map[string]*packageData{}

	for _, pkg := range pkgs {
		for _, file := range pkg.Syntax {
			for _, decl := range file.Decls {
				genDecl, ok := decl.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE {
					continue
				}
				for _, spec := range genDecl.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}

					doc := genDecl.Doc
					if typeSpec.Doc != nil {
						doc = typeSpec.Doc
					}
					if doc == nil || !strings.Contains(doc.Text(), "generate:reset") {
						continue
					}

					structType, ok := typeSpec.Type.(*ast.StructType)
					if !ok {
						continue
					}

					var entries []templateEntry
					for _, field := range structType.Fields.List {
						for _, name := range field.Names { // ВСЕ имена, не только [0]
							entries = append(entries, templateEntry{
								Name:      name.Name,
								TypeValue: getFieldType(field),
							})
						}
					}

					dir := packageDir(pkg)
					pd, ok := packagesMap[dir]
					if !ok {
						pd = &packageData{Package: pkg.Name, Path: dir}
						packagesMap[dir] = pd
					}
					pd.Structs = append(pd.Structs, structData{
						Type:    typeSpec.Name.Name,
						Entries: entries,
					})
				}
			}
		}
	}

	// запись, после полного сбора данных
	tmpl := template.Must(template.New("reset").Parse(templateStr))
	for _, pd := range packagesMap {
		var buf bytes.Buffer
		if err := tmpl.Execute(&buf, pd); err != nil {
			panic(err)
		}
		bufFmt, err := format.Source(buf.Bytes())
		if err != nil {
			panic(err)
		}
		if err := os.WriteFile(pd.Path+"/reset.gen.go", bufFmt, 0644); err != nil {
			panic(err)
		}
	}

}

func packageDir(pkg *packages.Package) string {
	if len(pkg.GoFiles) > 0 {
		return filepath.Dir(pkg.GoFiles[0])
	}
	if len(pkg.CompiledGoFiles) > 0 {
		return filepath.Dir(pkg.CompiledGoFiles[0])
	}
	return ""
}

func getFieldType(field *ast.Field) string {
	switch t := field.Type.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "pointer"
	case *ast.ArrayType:
		return "slice"
	case *ast.MapType:
		return "map"
	default:
		return "unknown"
	}
}
