package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"html/template"
	"os"
	"strings"

	"golang.org/x/tools/go/packages"
)

type templateStruct struct {
	Package string
	Path    string
	Type    string
	Entries []templateEntry
}

type templateEntry struct {
	Name      string
	typeValue any
}

const templateStr = `
// Code generated by go generate; DO NOT EDIT.

package {{.Package}}


func (t *{{.Type}}) Reset() {
}
`

func main() {
	flag.Parse()

	fmt.Println(flag.Args())
	cfg := &packages.Config{
		Mode:  packages.NeedName | packages.NeedFiles | packages.NeedSyntax,
		Tests: false,
	}

	pkgs, err := packages.Load(cfg, "github.com/Albert-Ti/go-musthave-shortener-tpl/...")
	if err != nil {
		panic(err)
	}

	templateStruct := templateStruct{}
	entries := []templateEntry{}

	for _, pkg := range pkgs {
		for _, file := range pkg.Syntax {
			for _, decls := range file.Decls {
				genDecl, ok := decls.(*ast.GenDecl)
				if !ok {
					continue
				}
				if genDecl.Tok != token.TYPE {
					continue
				}
				for _, spec := range genDecl.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					if strings.Contains(genDecl.Doc.Text(), "generate:reset") {

						templateStruct.Package = pkg.Name
						templateStruct.Type = typeSpec.Name.Name
						templateStruct.Path = pkg.Dir
						if structType, ok := typeSpec.Type.(*ast.StructType); ok {
							for _, field := range structType.Fields.List {
								if len(field.Names) > 0 {
									entries = append(entries, templateEntry{
										Name:      field.Names[0].Name,
										typeValue: getFieldType(field),
									})
								}
							}
						}
					}
				}
			}
		}
	}

	templateStruct.Entries = entries
	fname := "reset.gen.go"

	// генерируем код по шаблону
	tmpl, err := template.New("reset").Parse(templateStr)
	if err != nil {
		panic(err)
	}

	var buf bytes.Buffer
	err = tmpl.Execute(&buf, templateStruct)
	if err != nil {
		panic(err)
	}

	// форматируем код
	bufFmt, err := format.Source(buf.Bytes())
	if err != nil {
		panic(err)
	}

	// записываем сгенерированный код в файл
	err = os.WriteFile(templateStruct.Path+"/"+fname, bufFmt, 0644)
	if err != nil {
		panic(err)
	}
}

func getFieldType(field *ast.Field) string {
	it := field.Type.(*ast.Ident)
	return it.String()
}
