// Code generated by go generate; DO NOT EDIT.

package middleware

func (t *MyCustomClaims) Reset() {
	if t == nil {
		return
	}

	t.UserID = ""
}
func (t *gzipPool) Reset() {
	if t == nil {
		return
	}

	// Сложный тип t.mu
	t.free = t.free[:0]
}
func (t *responseData) Reset() {
	if t == nil {
		return
	}

	t.size = 0
	t.status = 0
	t.body = ""
}
