// Code generated by go generate; DO NOT EDIT.

package middleware

func (t *MyCustomClaims) Reset() {
	if t == nil {
		return
	}

	t.UserID = ""
}

func (t *responseData) Reset() {
	if t == nil {
		return
	}

	t.size = 0
	t.status = 0
	t.body = ""
}
