// Code generated by go generate; DO NOT EDIT.

package audit

func (t *AuditLog) Reset() {
	if t == nil {
		return
	}

	t.TS = 0
	t.Action = ""
	t.UserID = ""
	t.URL = ""
}

func (t *Auditor) Reset() {
	if t == nil {
		return
	}

	clear(t.action)
	t.observer = t.observer[:0]
	t.bufSize = 0
	t.workers = 0
}
