// Code generated by go generate; DO NOT EDIT.

package audit

func (t *AuditLog) Reset() {
	if t == nil {
		return
	}

	t.TS = 0
	t.Action = ""
	t.UserID = ""
	t.URL = ""
}

func (t *Auditor) Reset() {
	if t == nil {
		return
	}

	// Сложный тип t.ch
	t.action = nil
	t.observer = t.observer[:0]
	t.bufSize = 0
	t.workers = 0
	// Сложный тип t.wg
	// Сложный тип t.active
}
