// Code generated by go generate; DO NOT EDIT.

package testreset

func (t *ResetableStruct) Reset() {
	if t == nil {
		return
	}

	t.i = 0
	t.str = ""
	t.s = t.s[:0]
	clear(t.m)

	if t.iP != nil {
		*t.iP = 0
	}
	if t.strP != nil {
		*t.strP = ""
	}
	if t.sP != nil {
		*t.sP = (*t.sP)[:0]
	}
	if t.mP != nil {
		clear(*t.mP)
	}
	// Сложный тип t.child
}
