// Code generated by go generate; DO NOT EDIT.

package config

func (t *Options) Reset() {
	if t == nil {
		return
	}

	t.RunAddr = ""
	t.BaseURL = ""
	t.FileStoragePath = ""
	t.DatabaseDSN = ""
	t.JWTSecretKey = ""
	t.AuditFile = ""
	t.AuditURL = ""
	t.Mode = ""
}
